### ISSUE TITLE
新版热键管理点击插件选择和回调函数，程序回自动错位

### ISSUE THREAD

**Issue by imnono** [yjmthu/Neobox#11]
![image](https://user-images.githubusercontent.com/31657315/212234253-bff68716-59c6-4a30-b01d-29e9d1ab14c7.png)
如图，下拉框选则的是原来窗口的位置

**Comment by imnono** [comment]
报错热键报错
![image](https://user-images.githubusercontent.com/31657315/212234576-9b42c7b3-7e1b-44ed-a36b-0448a9f63bb3.png)

**Comment by yjmthu** [comment]
先点击左下角的加号，添加一个热键，然后才可以编辑，报存

**Comment by yjmthu** [comment]
点击按钮、下拉框的时候不要挪动鼠标，会造成窗口移动。这个不是特别影响使用，Qt无边框窗口就是这样，我到时候想想办法。

**Comment by imnono** [comment]
> 先点击左下角的加号，添加一个热键，然后才可以编辑，保存

可以加了，左下角的加减符合不显眼，可以用中文 新增热键/删除热键

**Comment by yjmthu** [comment]
好的。这里还有一个Bug，就是不能对空的热键按下减号，程序会崩溃。

**Comment by imnono** [comment]
> 好的。这里还有一个Bug，就是不能对空的热键按下减号按钮，程序会崩溃。
判断下，无热键的时候，检号按钮置灰，不可点击
