### ISSUE TITLE
关于neobox建议

### ISSUE THREAD

**Issue by VistaQvQ** [yjmthu/Neobox#13]
1，蓝色文字提示不易辨识!（参考截图）[mmexport1678665974234.png](https://user-images.githubusercontent.com/23132799/224582628-42ad5468-1eee-40ba-a010-2a5a51007d99.png)
![mmexport1678665967836.png](https://user-images.githubusercontent.com/23132799/224582633-d0f8054c-0407-4dbc-a96c-ffa1f0871a6f.png)
2，容易打开多个实例，建议加限制
![mmexport1678666051456.png](https://user-images.githubusercontent.com/23132799/224582745-baca01e6-df51-4a95-85ad-7babe8d98229.png)
3，不明原因错误（如截图）
![IMG_20230313_081358.png](https://user-images.githubusercontent.com/23132799/224582875-cec7c952-30ba-4426-90d3-1ac49b402f85.png)

**Comment by yjmthu** [comment]
好的，前两个问题正在改，第三个问题需要下载最新的neobox，目前是v2.3.5

**Comment by yjmthu** [comment]
问题1，2目前已经在最新版本[![Latest release version](https://img.shields.io/github/v/release/yjmthu/Neobox?color=red)](https://github.com/yjmthu/Neobox/releases/latest)解决。如果还有任何问题欢迎提新的issue。
