### ISSUE TITLE
报错了，提示无法找到某dll入口

### ISSUE THREAD

**Issue by VistaQvQ** [yjmthu/Neobox#14]
![IMG_20230419_145503.png](https://user-images.githubusercontent.com/23132799/232991358-4e135ed7-aadc-4c44-8b64-45f5db36aad5.png)
如截图所示，暂时不清楚产生此种情况的原因，删掉重装了

**Comment by yjmthu** [comment]
这个升级一下相关插件就好了

**Comment by VistaQvQ** [comment]
> 这个升级一下相关插件就好了。每次更新完主程序都建议更新插件。

插件升级他就报错了，卸载插件后在安装还是出错

**Comment by yjmthu** [comment]
那你现在使用的是2.3.7版本的neobox吗

**Comment by VistaQvQ** [comment]
> 那你现在使用的是2.3.7版本的neobox吗

2.3.6

**Comment by VistaQvQ** [comment]
> 那你现在使用的是2.3.7版本的neobox吗

更换2.3.7解决了，thx
