### ISSUE TITLE
窗口消失后再也找不到窗口了

### ISSUE THREAD

**Issue by yaaisinile** [yjmthu/Neobox#2]
拖动网速窗口碰到任务栏后窗口消失，进程还在，窗口不见了，重新运行也看不到窗口。建议增加一个任务栏图标

**Comment by yjmthu** [comment]
不错, 可以考虑增加个任务栏图标, 默认开启, 可以选择性关闭.
这个问题暂时可以通过修改目录`C:\Users\你的用户名\AppData\Local\SpeedBox`下的SpeedBox.ini文件中**\[UI\]**下面的x,y值来修改网速窗口的位置坐标, 如下图所示
![4V59Q337S~~{576HP{T6{9J](https://user-images.githubusercontent.com/73242138/148327870-5852c28b-a557-4e77-a82c-f26776304998.png)
建议一开始把x, y调节到100, 100的位置, 然后保存文件(注意不能改变文件编码格式, 仍为utf-8), 这样会保证它不在屏幕外.
然后在任务管理器中结束进程, 重新打开SpeedBox.exe即可. 这个bug我会在找到原因后修复.
另外我想问的是你的任务栏在屏幕的哪个位置(左,右,上,下)? 还有就是你的频率分辨率和缩放比例?
以及你的SpeedBox.ini文件里面修改前的x, y各是多少?

**Comment by yaaisinile** [comment]
多谢，已解决



***@***.***
 
发件人： Wiley2046
发送时间： 2022-01-06 12:31
收件人： yjmthu/Speed-Box
抄送： yaaisinile; Author
主题： Re: [yjmthu/Speed-Box] 窗口消失后再也找不到窗口了 (Issue #2)
不错, 可以考虑增加个任务栏图标, 默认开启, 可以选择性关闭.
这个问题暂时可以通过修改目录C:\Users\你的用户名\AppData\Local\SpeedBox下的SpeedBox.ini文件中**[UI]**下面的x,y值来修改网速窗口的位置坐标, 如下图所示

建议一开始把x, y调节到100, 100的位置, 然后保存文件(注意不能改变文件编码格式, 仍为utf-8), 这样会保证它不在屏幕外.
然后在任务管理器中结束进程, 重新打开SpeedBox.exe即可. 这个bug我会在找到原因后修复.
另外我想问的是你的任务栏在屏幕的哪个位置(左,右,上,下)? 还有就是你的频率分辨率和缩放比例?
以及你的SpeedBox.ini文件里面修改前的x, y各是多少?
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by yjmthu** [comment]
其实你的情况应该是网速悬浮窗自动贴边隐藏了，隐藏后你只要把鼠标移动到边上就可以重新显示。如果你不幸点击了任务栏，任务栏会覆盖网速悬浮窗，这样你就再也点不到它了，这种情况你可以隐藏任务栏或者把任务栏拖到一边。新版本我会尝试增加一个再次双击程序激活网速悬浮窗到界面最顶层的功能。

**Comment by yaaisinile** [comment]
我在拖动到右下角的任务栏处消失的，后面用彗星小助手拖出来的时候悬浮窗是从左下角出来的



***@***.***
 
发件人： Wiley2046
发送时间： 2022-01-06 18:50
收件人： yjmthu/Speed-Box
抄送： yaaisinile; Author
主题： Re: [yjmthu/Speed-Box] 窗口消失后再也找不到窗口了 (Issue #2)
其实你的情况应该是网速悬浮窗自动贴边隐藏了，隐藏后你只要把鼠标移动到边上就可以重新显示。如果你不幸点击了任务栏，任务栏会覆盖网速悬浮窗，这样你就再也点不到它了，这种情况你可以隐藏任务栏或者把任务栏拖到一边。新版本我会尝试增加一个再次双击程序激活网速悬浮窗到界面最顶层的功能。
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
