### ISSUE TITLE
划词翻译功能开关

### ISSUE THREAD

**Issue by yaaisinile** [yjmthu/Neobox#4]
按shift+z弹出翻译窗口后我习惯点X关闭翻译窗口，这样划词翻译的功能会被直接关闭，下次无法再用shift+z呼出窗口，右键菜单上划词翻译对应的✔也没了，要重新勾选才可以

**Comment by yaaisinile** [comment]
可能说的有些乱，就是我希望我关闭划词的窗口只是关闭了这个窗口，而不是关闭了这个功能

**Comment by yjmthu** [comment]
按shif+a或者esc键也可以隐藏窗口的，点右上角那个绿色横线也可以隐藏窗口，点右上角那个红色叉叉是关闭功能。

其实我也觉得用红色叉叉关闭功能有些不方便，所以我打算在将来把它设置成隐藏窗口。

**Comment by yaaisinile** [comment]
感谢回复！我实在没找到比这个方便好用的快捷翻译工具，只能来求助了。今天才发现是因为关闭窗口=关闭划词功能才导致后续无法弹出翻译窗口




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年4月18日(星期一) 下午3:57
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [yjmthu/Neobox] 划词翻译功能开关 (Issue #4)





 
按shif+a或者esc键也可以隐藏窗口的，点右上角那个绿色横线也可以隐藏窗口，点右上角那个红色叉叉是关闭功能。
 
其实我也觉得用红色叉叉关闭功能有些不方便，所以我打算在将来把它设置成隐藏窗口。

**Comment by yjmthu** [comment]
翻译的话我做了一个命令行版本的，显示的内容比较详细，但是需要打开终端。我想在SpeedBox里面也加入详细的翻译结果，奈何界面太小。

![image](https://user-images.githubusercontent.com/73242138/163787154-5c63e3bd-2da3-41ae-a08d-314af0807016.png)
