### ISSUE TITLE
建议：极简翻译记录窗体大小及窗体位置

### ISSUE THREAD

**Issue by imnono** [yjmthu/Neobox#5]
1、网速功能一般放在角落，每次打开极简翻译，都是贴近角落位置，使用不方便
建议，记录窗体位置
2、某些翻译内容较多的时候，会将窗体拉大，但是重新打开极简翻译，大小又会回到初始大小
建议，记录窗体大小，或者根据翻译内容，自适应放大窗体（限制最大窗体大小）
3、默认皮肤很好看，想了解下如果更换字体

**Comment by yjmthu** [comment]
感谢建议。1、2点我会在接下来的更新里面尝试改变。第3点，自带皮肤随插件更新，用户是无法改动的。不过你可以自己把默认皮肤模板修改一下，成为一个自己新建的皮肤。这需要一点Qt的知识，不知道你是否了解Qt的ui文件？或者你说明一下你想要的字体，我把修改后的皮肤代码贴给你。

**Comment by imnono** [comment]
> 感谢建议。1、2点我会在接下来的更新里面尝试改变。第3点，自带皮肤随插件更新，用户是无法改动的。不过你可以自己把默认皮肤模板修改一下，成为一个自己新建的皮肤。这需要一点Qt的知识，不知道你是否了解Qt的ui文件？或者你说明一下你想要的字体，我把修改后的皮肤代码和操作方法写给你。

我不会哎，可以给我弄一个微软雅黑light的字体吗，感激不尽~~~

**Comment by yjmthu** [comment]
> > 感谢建议。1、2点我会在接下来的更新里面尝试改变。第3点，自带皮肤随插件更新，用户是无法改动的。不过你可以自己把默认皮肤模板修改一下，成为一个自己新建的皮肤。这需要一点Qt的知识，不知道你是否了解Qt的ui文件？或者你说明一下你想要的字体，我把修改后的皮肤代码和操作方法写给你。
> 
> 我不会哎，可以给我弄一个微软雅黑light的字体吗，感激不尽~~~

网速和内存都是微软雅黑吗，我在我的电脑上找到了名字是“Microsoft YaHei UI Light”的字体，不知道是不是你说的那种

**Comment by imnono** [comment]
> > > 感谢建议。1、2点我会在接下来的更新里面尝试改变。第3点，自带皮肤随插件更新，用户是无法改动的。不过你可以自己把默认皮肤模板修改一下，成为一个自己新建的皮肤。这需要一点Qt的知识，不知道你是否了解Qt的ui文件？或者你说明一下你想要的字体，我把修改后的皮肤代码和操作方法写给你。
> > 
> > 
> > 我不会哎，可以给我弄一个微软雅黑light的字体吗，感激不尽~~~
> 
> 网速和内存都是微软雅黑吗，我在我的电脑上找到了名字是“Microsoft YaHei UI Light”的字体，不知道是不是你说的那种

网速和内存都是微软雅黑，就是“Microsoft YaHei UI Light”的字体

**Comment by yjmthu** [comment]
[imnono.txt](https://github.com/yjmthu/Neobox/files/10285060/imnono.txt)
你可以下载这个文件，把后缀txt改成ui（因为这里不支持上传ui文件），然后把它拖到悬浮窗里面，会弹出这样一个对话框：
![image](https://user-images.githubusercontent.com/73242138/209090825-1f71e7bb-a2b2-4d80-9243-d32bfe0282f1.png)
你随便取一个名字就行，例如 `imnono` ，然后点击 `OK` 。这样你就可以在右键菜单里面找到一个名字叫做 `imnono` 的皮肤了。

**Comment by imnono** [comment]
> [imnono.txt](https://github.com/yjmthu/Neobox/files/10285060/imnono.txt) 你可以下载这个文件，把后缀txt改成ui（因为这里不支持上传ui文件），然后把它拖到悬浮窗里面，会弹出这样一个对话框： ![image](https://user-images.githubusercontent.com/73242138/209090825-1f71e7bb-a2b2-4d80-9243-d32bfe0282f1.png) 你随便取一个名字就行，例如 `imnono` ，然后点击 `OK` 。这样你就可以在右键菜单里面找到一个名字叫做 `imnono` 的皮肤了。

感谢哦，已经安装成功~~

**Comment by yjmthu** [comment]
极简翻译更新已经上传，你可以看看右键菜单里面增加的项目是不是你想要的功能

**Comment by yjmthu** [comment]
没有事情我就关闭了哈，有问题就提新issue

**Comment by VistaQvQ** [comment]
皮肤的事情曾经有过提issue的念头，本考虑做提个动效的的建议，有点类似某输入法皮肤的思路。动手[基于好久之前的winform代码做了尝试](https://github.com/VistaQvQ/NetMonitor/releases/tag/%E4%BF%AE%E6%AD%A3%EF%BC%9A%E6%95%B0%E5%AD%97%E8%AE%A1%E7%AE%97%E6%98%BE%E7%A4%BA%E9%80%BB%E8%BE%91)，实现过程中发现细节挺多的。一般出在图片的压缩算法和图片容器本身对颜色的处理上，具体来说一些图片处理过程中免不了缩放，缩放的颜色管理不恰当比如仿色，抗锯齿写的不合理，再或者以为是白色实际上是（249，249，249）😂😂~~本想研究一下QT把想法付诸实践的，奈何上班过于开心以致下班需要平复心情~~其实不想把一些事情当成任务处理，加上自己状态也不太好，就先搁置一段时间。
如果需要，可以提新issue详细说明一下想法🌚
> 没有事情我就关闭了哈，有问题就提新issue
