### ISSUE TITLE
防息屏功能

### ISSUE THREAD

**Issue by jcmyt** [yjmthu/Neobox#6]
防止息屏功能现在是 不太好用 ，每次都必须得重新点击下才起作用。

**Comment by yjmthu** [comment]
重新点击是什么意思，是说软件每次启动后，防止息屏选项是未勾选的状态吗？

**Comment by yjmthu** [comment]
确实有个Bug。我刚刚更新了这个插件，你更新一下试试？

**Comment by yjmthu** [comment]
目前该问题已经修复。如果还有新的问题，就提新 [issue](https://github.com/yjmthu/Neobox/issues/new) 吧。
