### ISSUE TITLE
极简翻译出现202

### ISSUE THREAD

**Issue by imnono** [yjmthu/Neobox#7]
翻译中文出现202数字，如图
![image](https://user-images.githubusercontent.com/31657315/209782193-aa0da974-df1b-4b12-927e-3b358cfc656a.png)

**Comment by yjmthu** [comment]
一直有这个问题，我当初也不明白是为什么。刚刚又仔细试了一下，发现只要存在中文，且文本过长就不能正确翻译。我试试找下原因

**Comment by yjmthu** [comment]
我懂了，在生成input的时候字符串长度不能取utf-8串长度，而是字符个数。等会我会修复这个并上传更新

**Comment by yjmthu** [comment]
![image](https://user-images.githubusercontent.com/73242138/209821960-5e7e5515-ef92-47ff-b832-0cb43d4ca14d.png)

我这边没问题了，你更新试试

**Comment by imnono** [comment]
![image](https://user-images.githubusercontent.com/31657315/209925680-d91c0b71-78db-49bb-9d3d-49feed53ce04.png)
偶发出现207

**Comment by imnono** [comment]
![image](https://user-images.githubusercontent.com/31657315/209925752-62b542f5-fbc6-449c-aa4c-a373743db7bb.png)
在输入完需要翻译的文字后，一直重复不断的按回车，会有一定情况下出现

**Comment by yjmthu** [comment]
这个是翻译请求过于频繁导致的。那我再加个重复请求判断，如果和上次请求的内容一样就什么也不做。

**Comment by imnono** [comment]
> 这个是翻译请求过于频繁导致的。那我再加个重复请求判断，如果和上次请求的内容一样就什么也不做。

哈哈哈，顺便把输入框搞大一点吧，现在这个小的过分了。。。

**Comment by yjmthu** [comment]
OK，输入框已经恢复默认大小。但暂时还不能手动调大小，以后我会找时间增加这个功能。

**Comment by yjmthu** [comment]
嗨，新年好！现在极简翻译可以调节输入窗口高度了，鼠标放在彩色区域滚动滚轮就可以调节输入窗口大小。
![image](https://user-images.githubusercontent.com/73242138/210152957-1220946e-8822-410a-87f0-8307df2cf5a6.png)
