### ISSUE TITLE
老是崩溃，另外想问一下，网速的数据是怎么获取的

### ISSUE THREAD

**Issue by wslyx** [yjmthu/Neobox#8]

**Comment by yjmthu** [comment]
你现在使用的是哪几个插件，一般是什么时候崩溃的呢？

**Comment by yjmthu** [comment]
网速的获取可以看这个代码[文件](https://github.com/yjmthu/Neobox/blob/master/plugins/neospeedbox_core/src/netspeedhelper.cpp)，包括windows和Linux上网速、内存占用率的获取。其中linux部分目前肯定是编译不过了，仅供参考。

**Comment by yjmthu** [comment]
确实有一些造作会引起崩溃，在发现后我也都修复了。但是不知道你具体说的是什么情况下的崩溃，你可以试试更新Neobox和更新插件来解决。如果还有新的问题就请详细描述一下，再另外提出一个issue吧。
